FROM python:3.9.0
LABEL maintainer="burkh4rt"

WORKDIR /usr/src/

RUN apt-get update &&
    RUN apt-get update && apt-get install -y --no-install-recommends git &&
    RUN git clone https://github.com/burkh4rt/miracl-core.git &&
    RUN cd miracl-core &&
    RUN git checkout -b dev-python-autoconfiguration -fq a1c831f &&
    RUN cd .. &&
    RUN cp ./miracl-core/python/* . &&
    RUN rm -rf ./miracl-core/ &&
    RUN python auto_config.py 8

COPY . .

RUN echo "Testing Mercurial Singature Scheme..."
RUN python test_mercurial_signature_scheme.py

RUN echo "Testing Delegatable Anonymous Credential Scheme..."
RUN python test_delegatable_anon_cred_scheme.py
